/**
 * GitHub Service
 * Handles interactions with GitHub API for comments and PR operations
 */

import { Octokit } from '@octokit/rest';
import type { PullRequestEvent } from '../types/index.js';

interface GitHubConfig {
  token?: string;
  appId?: number;
  privateKey?: string;
}

export class GitHubService {
  private octokit: Octokit;
  private appOctokit?: Octokit;

  constructor(config: GitHubConfig) {
    this.octokit = new Octokit({
      auth: config.token,
    });

    if (config.appId && config.privateKey) {
      this.appOctokit = new Octokit({
        auth: async () => {
          // In production, implement JWT authentication for GitHub App
          // For now, use the provided token
          return config.token || '';
        },
      });
    }
  }

  /**
   * Get the appropriate Octokit instance (app or token-based)
   */
  private getOctokit(owner: string): Octokit {
    return this.appOctokit || this.octokit;
  }

  /**
   * Post a comment on a PR with the preview URL
   */
  async postPreviewComment(
    owner: string,
    repo: string,
    prNumber: number,
    previewUrl: string,
    workspaceId: string
  ): Promise<number> {
    const client = this.getOctokit(owner);

    const commentBody = this.generatePreviewComment(previewUrl, workspaceId);

    const response = await client.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: commentBody,
    });

    console.log(`[GitHub] Posted preview comment #${response.data.id} on PR #${prNumber}`);
    return response.data.id;
  }

  /**
   * Update an existing preview comment
   */
  async updatePreviewComment(
    owner: string,
    repo: string,
    commentId: number,
    previewUrl: string,
    workspaceId: string
  ): Promise<void> {
    const client = this.getOctokit(owner);

    const commentBody = this.generatePreviewComment(previewUrl, workspaceId);

    await client.issues.updateComment({
      owner,
      repo,
      comment_id: commentId,
      body: commentBody,
    });

    console.log(`[GitHub] Updated preview comment #${commentId}`);
  }

  /**
   * Delete a comment on a PR
   */
  async deletePreviewComment(
    owner: string,
    repo: string,
    commentId: number
  ): Promise<void> {
    const client = this.getOctokit(owner);

    await client.issues.deleteComment({
      owner,
      repo,
      comment_id: commentId,
    });

    console.log(`[GitHub] Deleted preview comment #${commentId}`);
  }

  /**
   * Find existing preview comment by this bot
   */
  async findExistingPreviewComment(
    owner: string,
    repo: string,
    prNumber: number,
    botLogin: string
  ): Promise<{ id: number } | null> {
    const client = this.getOctokit(owner);

    const response = await client.issues.listComments({
      owner,
      repo,
      issue_number: prNumber,
      per_page: 100,
    });

    // Find the most recent comment from this bot with preview content
    const botComment = response.data
      .filter((comment) => comment.user?.login === botLogin)
      .find((comment) => comment.body.includes('🚀 PR Preview Ready'))
      .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())[0];

    return botComment ? { id: botComment.id } : null;
  }

  /**
   * Get PR details
   */
  async getPRDetails(
    owner: string,
    repo: string,
    prNumber: number
  ): Promise<PullRequestEvent['pull_request'] | null> {
    const client = this.getOctokit(owner);

    try {
      const response = await client.pulls.get({
        owner,
        repo,
        pull_number: prNumber,
      });

      return response.data as PullRequestEvent['pull_request'];
    } catch (error) {
      console.error(`[GitHub] Failed to get PR #${prNumber} details:`, error);
      return null;
    }
  }

  /**
   * Get the bot's login name
   */
  async getBotLogin(): Promise<string> {
    try {
      const response = await this.octokit.users.getAuthenticated();
      return response.data.login;
    } catch {
      return 'github-app[bot]';
    }
  }

  /**
   * Generate the preview comment body
   */
  private generatePreviewComment(previewUrl: string, workspaceId: string): string {
    return `🚀 **PR Preview Ready**

Your preview environment is ready! Click the link below to view the live preview:

🔗 **[Open Preview](${previewUrl})**

**Workspace ID:** \`${workspaceId}\`

---
*Powered by PR Preview Studio*
*This comment was automatically generated by the PR Preview GitHub App*`;
  }

  /**
   * Generate cleanup comment
   */
  generateCleanupComment(workspaceId: string): string {
    return `🧹 **Workspace Cleanup**

This preview workspace has been cleaned up.

**Workspace ID:** \`${workspaceId}\`

---
*PR Preview Studio - Cleanup complete*`;
  }

  /**
   * Post cleanup comment
   */
  async postCleanupComment(
    owner: string,
    repo: string,
    prNumber: number,
    workspaceId: string
  ): Promise<void> {
    const client = this.getOctokit(owner);

    const commentBody = this.generateCleanupComment(workspaceId);

    await client.issues.createComment({
      owner,
      repo,
      issue_number: prNumber,
      body: commentBody,
    });

    console.log(`[GitHub] Posted cleanup comment on PR #${prNumber}`);
  }
}

// Export factory function
export function createGitHubService(): GitHubService {
  return new GitHubService({
    token: process.env.GITHUB_TOKEN || process.env.GH_TOKEN,
    appId: process.env.GITHUB_APP_ID ? parseInt(process.env.GITHUB_APP_ID, 10) : undefined,
    privateKey: process.env.GITHUB_PRIVATE_KEY,
  });
}
